http:
  adminPort: 8082
  port: 9193
  requestLog:
    console:
      enabled: false
    file:
      enabled: false

logging:

  level: WARN

  console:
    enabled: true
    threshold: ALL

  file:
    enabled: false
    threshold: ALL
    currentLogFilename: ./logs/example.log
    archivedLogFilenamePattern: ./logs/example-%d.log.gz
    archivedFileCount: 5

  syslog:
    enabled: false
    host: localhost
    facility: local0
